# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SettingsWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SettingsWindow(object):
    def setupUi(self, SettingsWindow):
        SettingsWindow.setObjectName("SettingsWindow")
        SettingsWindow.resize(610, 654)
        SettingsWindow.setMinimumSize(QtCore.QSize(574, 591))
        SettingsWindow.setMaximumSize(QtCore.QSize(1000, 1000))
        SettingsWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(SettingsWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget_2.setStyleSheet("QListWidget {background-color: rbg(30, 30, 30)}\n"
"QComboBox {color: white}")
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout_35 = QtWidgets.QGridLayout()
        self.gridLayout_35.setObjectName("gridLayout_35")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_35.addItem(spacerItem, 0, 0, 1, 1)
        self.DFT_label_20 = QtWidgets.QLabel(self.tab_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DFT_label_20.sizePolicy().hasHeightForWidth())
        self.DFT_label_20.setSizePolicy(sizePolicy)
        self.DFT_label_20.setMinimumSize(QtCore.QSize(100, 0))
        self.DFT_label_20.setMaximumSize(QtCore.QSize(300, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.DFT_label_20.setFont(font)
        self.DFT_label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.DFT_label_20.setObjectName("DFT_label_20")
        self.gridLayout_35.addWidget(self.DFT_label_20, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_35.addItem(spacerItem1, 0, 2, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_35)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.tab_4)
        self.label_3.setMaximumSize(QtCore.QSize(125, 16777215))
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.cwd_lineEdit = QtWidgets.QLineEdit(self.tab_4)
        self.cwd_lineEdit.setMinimumSize(QtCore.QSize(50, 0))
        self.cwd_lineEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.cwd_lineEdit.setObjectName("cwd_lineEdit")
        self.horizontalLayout_2.addWidget(self.cwd_lineEdit)
        self.change_cwd_button = QtWidgets.QPushButton(self.tab_4)
        self.change_cwd_button.setMinimumSize(QtCore.QSize(100, 0))
        self.change_cwd_button.setMaximumSize(QtCore.QSize(120, 16777215))
        self.change_cwd_button.setObjectName("change_cwd_button")
        self.horizontalLayout_2.addWidget(self.change_cwd_button)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 130, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_4 = QtWidgets.QLabel(self.tab_4)
        self.label_4.setMaximumSize(QtCore.QSize(125, 16777215))
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_9.addWidget(self.label_4)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pymol_lineEdit = QtWidgets.QLineEdit(self.tab_4)
        self.pymol_lineEdit.setMinimumSize(QtCore.QSize(50, 0))
        self.pymol_lineEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pymol_lineEdit.setObjectName("pymol_lineEdit")
        self.horizontalLayout_6.addWidget(self.pymol_lineEdit)
        self.change_pymol_button = QtWidgets.QPushButton(self.tab_4)
        self.change_pymol_button.setMinimumSize(QtCore.QSize(100, 0))
        self.change_pymol_button.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.change_pymol_button.setObjectName("change_pymol_button")
        self.horizontalLayout_6.addWidget(self.change_pymol_button)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.open_pymol_checkBox = QtWidgets.QCheckBox(self.tab_4)
        self.open_pymol_checkBox.setMinimumSize(QtCore.QSize(130, 0))
        self.open_pymol_checkBox.setMaximumSize(QtCore.QSize(130, 310))
        font = QtGui.QFont()
        font.setItalic(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.open_pymol_checkBox.setFont(font)
        self.open_pymol_checkBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.open_pymol_checkBox.setAutoFillBackground(False)
        self.open_pymol_checkBox.setObjectName("open_pymol_checkBox")
        self.horizontalLayout_10.addWidget(self.open_pymol_checkBox)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem5)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        spacerItem6 = QtWidgets.QSpacerItem(20, 130, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem6)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem7)
        self.DFT_label_21 = QtWidgets.QLabel(self.tab_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(150)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DFT_label_21.sizePolicy().hasHeightForWidth())
        self.DFT_label_21.setSizePolicy(sizePolicy)
        self.DFT_label_21.setMinimumSize(QtCore.QSize(20, 0))
        self.DFT_label_21.setMaximumSize(QtCore.QSize(80, 14))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.DFT_label_21.setFont(font)
        self.DFT_label_21.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.DFT_label_21.setObjectName("DFT_label_21")
        self.horizontalLayout_11.addWidget(self.DFT_label_21)
        self.radioButton_ORCA = QtWidgets.QRadioButton(self.tab_4)
        self.radioButton_ORCA.setObjectName("radioButton_ORCA")
        self.horizontalLayout_11.addWidget(self.radioButton_ORCA)
        self.radioButton_Gaussian = QtWidgets.QRadioButton(self.tab_4)
        self.radioButton_Gaussian.setObjectName("radioButton_Gaussian")
        self.horizontalLayout_11.addWidget(self.radioButton_Gaussian)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem8)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.save_button_0 = QtWidgets.QPushButton(self.tab_4)
        self.save_button_0.setMinimumSize(QtCore.QSize(100, 25))
        self.save_button_0.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.save_button_0.setFont(font)
        self.save_button_0.setStyleSheet("QPushButton {\n"
"     background-color: rgb(143, 23, 119);\n"
"       color: white;\n"
" }\n"
" QPushButton:hover{\n"
" background-color:rgb(143, 23, 119);\n"
" border-style: outset;\n"
" border-width: 0px;\n"
" /*border-color: rgb(12, 103, 213);*/\n"
" }\n"
" QPushButton:pressed\n"
" {\n"
" /*background-color:rgb(17, 145, 255);\n"
"  color: black*/\n"
"  background-color: rgb(42, 42, 42);\n"
" }\n"
" QListWidget{\n"
" background-color: rgb(20,20,20);\n"
" border:None;\n"
" margin-top:0px;\n"
" margin-left:0px;\n"
" margin-right:0px;\n"
" }")
        self.save_button_0.setObjectName("save_button_0")
        self.horizontalLayout_25.addWidget(self.save_button_0)
        self.cancel_button_0 = QtWidgets.QPushButton(self.tab_4)
        self.cancel_button_0.setMinimumSize(QtCore.QSize(100, 25))
        self.cancel_button_0.setMaximumSize(QtCore.QSize(16777215, 25))
        self.cancel_button_0.setStyleSheet("\n"
"\n"
"QPushButton {\n"
"    /*background-color:rgb(98, 114, 164);*/\n"
"    background-color: rgb(30,30,30);\n"
"    color: rgb(143,23,119);\n"
"    \n"
"\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"       background-color: rgb(40, 40, 40);\n"
"    /*color:rgb(20,20,20);*/\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-color: rgb(143,23,119);\n"
"\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    color: rgb(143, 23, 119);\n"
"    background-color: rgb(20, 20, 20);\n"
"}\n"
"")
        self.cancel_button_0.setObjectName("cancel_button_0")
        self.horizontalLayout_25.addWidget(self.cancel_button_0)
        self.verticalLayout_3.addLayout(self.horizontalLayout_25)
        self.tabWidget_2.addTab(self.tab_4, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_8)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_23 = QtWidgets.QGridLayout()
        self.gridLayout_23.setObjectName("gridLayout_23")
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_23.addItem(spacerItem9, 0, 0, 1, 1)
        self.DFT_label_6 = QtWidgets.QLabel(self.tab_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DFT_label_6.sizePolicy().hasHeightForWidth())
        self.DFT_label_6.setSizePolicy(sizePolicy)
        self.DFT_label_6.setMinimumSize(QtCore.QSize(100, 0))
        self.DFT_label_6.setMaximumSize(QtCore.QSize(300, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.DFT_label_6.setFont(font)
        self.DFT_label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.DFT_label_6.setObjectName("DFT_label_6")
        self.gridLayout_23.addWidget(self.DFT_label_6, 0, 1, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_23.addItem(spacerItem10, 0, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_23)
        self.gridLayout_24 = QtWidgets.QGridLayout()
        self.gridLayout_24.setObjectName("gridLayout_24")
        self.funct_label_5 = QtWidgets.QLabel(self.tab_8)
        self.funct_label_5.setMinimumSize(QtCore.QSize(70, 0))
        self.funct_label_5.setMaximumSize(QtCore.QSize(70, 16777215))
        self.funct_label_5.setObjectName("funct_label_5")
        self.gridLayout_24.addWidget(self.funct_label_5, 0, 0, 1, 1)
        self.basis1_comboBox_orca = QtWidgets.QComboBox(self.tab_8)
        self.basis1_comboBox_orca.setMinimumSize(QtCore.QSize(100, 0))
        self.basis1_comboBox_orca.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.basis1_comboBox_orca.setEditable(True)
        self.basis1_comboBox_orca.setObjectName("basis1_comboBox_orca")
        self.gridLayout_24.addWidget(self.basis1_comboBox_orca, 1, 1, 1, 1)
        self.comboBox_funct_orca = QtWidgets.QComboBox(self.tab_8)
        self.comboBox_funct_orca.setMinimumSize(QtCore.QSize(100, 0))
        self.comboBox_funct_orca.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.comboBox_funct_orca.setEditable(True)
        self.comboBox_funct_orca.setObjectName("comboBox_funct_orca")
        self.gridLayout_24.addWidget(self.comboBox_funct_orca, 0, 1, 1, 1)
        self.basis_label_5 = QtWidgets.QLabel(self.tab_8)
        self.basis_label_5.setMinimumSize(QtCore.QSize(70, 0))
        self.basis_label_5.setMaximumSize(QtCore.QSize(70, 16777215))
        self.basis_label_5.setObjectName("basis_label_5")
        self.gridLayout_24.addWidget(self.basis_label_5, 1, 0, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_24.addItem(spacerItem11, 0, 2, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_24.addItem(spacerItem12, 1, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_24)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.line_25 = QtWidgets.QFrame(self.tab_8)
        self.line_25.setMinimumSize(QtCore.QSize(50, 0))
        self.line_25.setMaximumSize(QtCore.QSize(50, 16777215))
        self.line_25.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_25.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_25.setObjectName("line_25")
        self.horizontalLayout_17.addWidget(self.line_25)
        self.DFT_label_14 = QtWidgets.QLabel(self.tab_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(150)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DFT_label_14.sizePolicy().hasHeightForWidth())
        self.DFT_label_14.setSizePolicy(sizePolicy)
        self.DFT_label_14.setMinimumSize(QtCore.QSize(180, 0))
        self.DFT_label_14.setMaximumSize(QtCore.QSize(180, 14))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.DFT_label_14.setFont(font)
        self.DFT_label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.DFT_label_14.setObjectName("DFT_label_14")
        self.horizontalLayout_17.addWidget(self.DFT_label_14)
        self.line_26 = QtWidgets.QFrame(self.tab_8)
        self.line_26.setMinimumSize(QtCore.QSize(50, 0))
        self.line_26.setMaximumSize(QtCore.QSize(50, 16777215))
        self.line_26.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_26.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_26.setObjectName("line_26")
        self.horizontalLayout_17.addWidget(self.line_26)
        self.verticalLayout.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.job_type_comboBox_orca = QtWidgets.QComboBox(self.tab_8)
        self.job_type_comboBox_orca.setMinimumSize(QtCore.QSize(100, 0))
        self.job_type_comboBox_orca.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.job_type_comboBox_orca.setEditable(False)
        self.job_type_comboBox_orca.setObjectName("job_type_comboBox_orca")
        self.horizontalLayout_3.addWidget(self.job_type_comboBox_orca)
        self.jobspec_keywords_orca = QtWidgets.QLineEdit(self.tab_8)
        self.jobspec_keywords_orca.setMinimumSize(QtCore.QSize(250, 21))
        self.jobspec_keywords_orca.setMaximumSize(QtCore.QSize(16777215, 21))
        font = QtGui.QFont()
        font.setItalic(True)
        self.jobspec_keywords_orca.setFont(font)
        self.jobspec_keywords_orca.setInputMask("")
        self.jobspec_keywords_orca.setText("")
        self.jobspec_keywords_orca.setObjectName("jobspec_keywords_orca")
        self.horizontalLayout_3.addWidget(self.jobspec_keywords_orca)
        self.pushButton = QtWidgets.QPushButton(self.tab_8)
        self.pushButton.setMinimumSize(QtCore.QSize(30, 0))
        self.pushButton.setMaximumSize(QtCore.QSize(130, 16777215))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_3.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.add_jobspec_orca_list = QtWidgets.QListWidget(self.tab_8)
        self.add_jobspec_orca_list.setMinimumSize(QtCore.QSize(190, 50))
        self.add_jobspec_orca_list.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.add_jobspec_orca_list.setObjectName("add_jobspec_orca_list")
        self.horizontalLayout_4.addWidget(self.add_jobspec_orca_list)
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_8)
        self.pushButton_2.setMinimumSize(QtCore.QSize(130, 0))
        self.pushButton_2.setMaximumSize(QtCore.QSize(130, 16777215))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_4.addWidget(self.pushButton_2)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.line_27 = QtWidgets.QFrame(self.tab_8)
        self.line_27.setMinimumSize(QtCore.QSize(50, 0))
        self.line_27.setMaximumSize(QtCore.QSize(50, 16777215))
        self.line_27.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_27.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_27.setObjectName("line_27")
        self.horizontalLayout_18.addWidget(self.line_27)
        self.DFT_label_15 = QtWidgets.QLabel(self.tab_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(150)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DFT_label_15.sizePolicy().hasHeightForWidth())
        self.DFT_label_15.setSizePolicy(sizePolicy)
        self.DFT_label_15.setMinimumSize(QtCore.QSize(120, 0))
        self.DFT_label_15.setMaximumSize(QtCore.QSize(180, 14))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.DFT_label_15.setFont(font)
        self.DFT_label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.DFT_label_15.setObjectName("DFT_label_15")
        self.horizontalLayout_18.addWidget(self.DFT_label_15)
        self.line_28 = QtWidgets.QFrame(self.tab_8)
        self.line_28.setMinimumSize(QtCore.QSize(50, 0))
        self.line_28.setMaximumSize(QtCore.QSize(50, 16777215))
        self.line_28.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_28.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_28.setObjectName("line_28")
        self.horizontalLayout_18.addWidget(self.line_28)
        self.verticalLayout.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.inputblock_orca = QtWidgets.QComboBox(self.tab_8)
        self.inputblock_orca.setMinimumSize(QtCore.QSize(100, 0))
        self.inputblock_orca.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.inputblock_orca.setEditable(True)
        self.inputblock_orca.setObjectName("inputblock_orca")
        self.horizontalLayout_5.addWidget(self.inputblock_orca)
        self.additionalblock_orca = QtWidgets.QLineEdit(self.tab_8)
        self.additionalblock_orca.setMinimumSize(QtCore.QSize(250, 21))
        self.additionalblock_orca.setMaximumSize(QtCore.QSize(16777215, 21))
        font = QtGui.QFont()
        font.setItalic(True)
        self.additionalblock_orca.setFont(font)
        self.additionalblock_orca.setText("")
        self.additionalblock_orca.setObjectName("additionalblock_orca")
        self.horizontalLayout_5.addWidget(self.additionalblock_orca)
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_8)
        self.pushButton_3.setMinimumSize(QtCore.QSize(30, 0))
        self.pushButton_3.setMaximumSize(QtCore.QSize(130, 16777215))
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_5.addWidget(self.pushButton_3)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.add_list2_orca = QtWidgets.QListWidget(self.tab_8)
        self.add_list2_orca.setMinimumSize(QtCore.QSize(190, 50))
        self.add_list2_orca.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.add_list2_orca.setObjectName("add_list2_orca")
        self.horizontalLayout_8.addWidget(self.add_list2_orca)
        self.pushButton_4 = QtWidgets.QPushButton(self.tab_8)
        self.pushButton_4.setMinimumSize(QtCore.QSize(130, 0))
        self.pushButton_4.setMaximumSize(QtCore.QSize(130, 16777215))
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_8.addWidget(self.pushButton_4)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.save_button_1 = QtWidgets.QPushButton(self.tab_8)
        self.save_button_1.setMinimumSize(QtCore.QSize(100, 25))
        self.save_button_1.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.save_button_1.setFont(font)
        self.save_button_1.setStyleSheet("QPushButton {\n"
"     background-color: rgb(143, 23, 119);\n"
"       color: white;\n"
" }\n"
" QPushButton:hover{\n"
" background-color:rgb(143, 23, 119);\n"
" border-style: outset;\n"
" border-width: 0px;\n"
" /*border-color: rgb(12, 103, 213);*/\n"
" }\n"
" QPushButton:pressed\n"
" {\n"
" /*background-color:rgb(17, 145, 255);\n"
"  color: black*/\n"
"  background-color: rgb(42, 42, 42);\n"
" }\n"
" QListWidget{\n"
" background-color: rgb(20,20,20);\n"
" border:None;\n"
" margin-top:0px;\n"
" margin-left:0px;\n"
" margin-right:0px;\n"
" }")
        self.save_button_1.setObjectName("save_button_1")
        self.horizontalLayout_19.addWidget(self.save_button_1)
        self.cancel_button_1 = QtWidgets.QPushButton(self.tab_8)
        self.cancel_button_1.setMinimumSize(QtCore.QSize(100, 25))
        self.cancel_button_1.setMaximumSize(QtCore.QSize(16777215, 25))
        self.cancel_button_1.setStyleSheet("\n"
"\n"
"QPushButton {\n"
"    /*background-color:rgb(98, 114, 164);*/\n"
"    background-color: rgb(30,30,30);\n"
"    color: rgb(143,23,119);\n"
"    \n"
"\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"       background-color: rgb(40, 40, 40);\n"
"    /*color:rgb(20,20,20);*/\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-color: rgb(143,23,119);\n"
"\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    color: rgb(143, 23, 119);\n"
"    background-color: rgb(20, 20, 20);\n"
"}\n"
"")
        self.cancel_button_1.setObjectName("cancel_button_1")
        self.horizontalLayout_19.addWidget(self.cancel_button_1)
        self.verticalLayout.addLayout(self.horizontalLayout_19)
        self.tabWidget_2.addTab(self.tab_8, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.tab_5)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.gridLayout_27 = QtWidgets.QGridLayout()
        self.gridLayout_27.setObjectName("gridLayout_27")
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_27.addItem(spacerItem13, 0, 0, 1, 1)
        self.DFT_label_16 = QtWidgets.QLabel(self.tab_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DFT_label_16.sizePolicy().hasHeightForWidth())
        self.DFT_label_16.setSizePolicy(sizePolicy)
        self.DFT_label_16.setMinimumSize(QtCore.QSize(100, 0))
        self.DFT_label_16.setMaximumSize(QtCore.QSize(300, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.DFT_label_16.setFont(font)
        self.DFT_label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.DFT_label_16.setObjectName("DFT_label_16")
        self.gridLayout_27.addWidget(self.DFT_label_16, 0, 1, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_27.addItem(spacerItem14, 0, 2, 1, 1)
        self.verticalLayout_22.addLayout(self.gridLayout_27)
        self.gridLayout_28 = QtWidgets.QGridLayout()
        self.gridLayout_28.setObjectName("gridLayout_28")
        self.funct_label_6 = QtWidgets.QLabel(self.tab_5)
        self.funct_label_6.setMinimumSize(QtCore.QSize(70, 0))
        self.funct_label_6.setMaximumSize(QtCore.QSize(70, 16777215))
        self.funct_label_6.setObjectName("funct_label_6")
        self.gridLayout_28.addWidget(self.funct_label_6, 0, 0, 1, 1)
        self.comboBox_funct_gauss = QtWidgets.QComboBox(self.tab_5)
        self.comboBox_funct_gauss.setMinimumSize(QtCore.QSize(100, 0))
        self.comboBox_funct_gauss.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.comboBox_funct_gauss.setEditable(True)
        self.comboBox_funct_gauss.setObjectName("comboBox_funct_gauss")
        self.gridLayout_28.addWidget(self.comboBox_funct_gauss, 0, 1, 1, 1)
        self.basis_label_6 = QtWidgets.QLabel(self.tab_5)
        self.basis_label_6.setMinimumSize(QtCore.QSize(70, 0))
        self.basis_label_6.setMaximumSize(QtCore.QSize(70, 16777215))
        self.basis_label_6.setObjectName("basis_label_6")
        self.gridLayout_28.addWidget(self.basis_label_6, 1, 0, 1, 1)
        self.basis1_comboBox_gauss = QtWidgets.QComboBox(self.tab_5)
        self.basis1_comboBox_gauss.setMinimumSize(QtCore.QSize(100, 0))
        self.basis1_comboBox_gauss.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.basis1_comboBox_gauss.setEditable(True)
        self.basis1_comboBox_gauss.setObjectName("basis1_comboBox_gauss")
        self.gridLayout_28.addWidget(self.basis1_comboBox_gauss, 1, 1, 1, 1)
        self.gridLayout_29 = QtWidgets.QGridLayout()
        self.gridLayout_29.setObjectName("gridLayout_29")
        self.basis2_comboBox_gauss = QtWidgets.QComboBox(self.tab_5)
        self.basis2_comboBox_gauss.setMinimumSize(QtCore.QSize(53, 0))
        self.basis2_comboBox_gauss.setMaximumSize(QtCore.QSize(53, 16777215))
        self.basis2_comboBox_gauss.setEditable(True)
        self.basis2_comboBox_gauss.setObjectName("basis2_comboBox_gauss")
        self.gridLayout_29.addWidget(self.basis2_comboBox_gauss, 0, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.tab_5)
        self.label_14.setMinimumSize(QtCore.QSize(13, 26))
        self.label_14.setMaximumSize(QtCore.QSize(13, 16))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_14.setObjectName("label_14")
        self.gridLayout_29.addWidget(self.label_14, 0, 1, 1, 1)
        self.basis3_comboBox_gauss = QtWidgets.QComboBox(self.tab_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.basis3_comboBox_gauss.sizePolicy().hasHeightForWidth())
        self.basis3_comboBox_gauss.setSizePolicy(sizePolicy)
        self.basis3_comboBox_gauss.setMinimumSize(QtCore.QSize(65, 0))
        self.basis3_comboBox_gauss.setMaximumSize(QtCore.QSize(65, 16777215))
        self.basis3_comboBox_gauss.setEditable(True)
        self.basis3_comboBox_gauss.setObjectName("basis3_comboBox_gauss")
        self.gridLayout_29.addWidget(self.basis3_comboBox_gauss, 0, 2, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.tab_5)
        self.label_15.setMinimumSize(QtCore.QSize(16, 26))
        self.label_15.setMaximumSize(QtCore.QSize(16, 16))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_15.setObjectName("label_15")
        self.gridLayout_29.addWidget(self.label_15, 0, 3, 1, 1)
        self.basis4_comboBox_gauss = QtWidgets.QComboBox(self.tab_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.basis4_comboBox_gauss.sizePolicy().hasHeightForWidth())
        self.basis4_comboBox_gauss.setSizePolicy(sizePolicy)
        self.basis4_comboBox_gauss.setMinimumSize(QtCore.QSize(65, 0))
        self.basis4_comboBox_gauss.setMaximumSize(QtCore.QSize(51, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.basis4_comboBox_gauss.setFont(font)
        self.basis4_comboBox_gauss.setEditable(True)
        self.basis4_comboBox_gauss.setObjectName("basis4_comboBox_gauss")
        self.gridLayout_29.addWidget(self.basis4_comboBox_gauss, 0, 4, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.tab_5)
        self.label_16.setMinimumSize(QtCore.QSize(12, 26))
        self.label_16.setMaximumSize(QtCore.QSize(12, 16))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_16.setObjectName("label_16")
        self.gridLayout_29.addWidget(self.label_16, 0, 5, 1, 1)
        self.gridLayout_28.addLayout(self.gridLayout_29, 2, 1, 1, 2)
        self.verticalLayout_22.addLayout(self.gridLayout_28)
        self.additionalKeys1_gauss = QtWidgets.QLineEdit(self.tab_5)
        self.additionalKeys1_gauss.setMinimumSize(QtCore.QSize(190, 21))
        self.additionalKeys1_gauss.setMaximumSize(QtCore.QSize(16777215, 21))
        font = QtGui.QFont()
        font.setItalic(True)
        self.additionalKeys1_gauss.setFont(font)
        self.additionalKeys1_gauss.setText("")
        self.additionalKeys1_gauss.setObjectName("additionalKeys1_gauss")
        self.verticalLayout_22.addWidget(self.additionalKeys1_gauss)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.add_DFT_list1_gauss = QtWidgets.QListWidget(self.tab_5)
        self.add_DFT_list1_gauss.setMinimumSize(QtCore.QSize(190, 50))
        self.add_DFT_list1_gauss.setMaximumSize(QtCore.QSize(16777215, 200))
        self.add_DFT_list1_gauss.setStyleSheet("")
        self.add_DFT_list1_gauss.setObjectName("add_DFT_list1_gauss")
        self.horizontalLayout_20.addWidget(self.add_DFT_list1_gauss)
        self.verticalLayout_29 = QtWidgets.QVBoxLayout()
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.add_1_gauss = QtWidgets.QPushButton(self.tab_5)
        self.add_1_gauss.setMinimumSize(QtCore.QSize(24, 24))
        self.add_1_gauss.setMaximumSize(QtCore.QSize(24, 24))
        self.add_1_gauss.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/24x24/resources/icons/arrow-plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_1_gauss.setIcon(icon)
        self.add_1_gauss.setIconSize(QtCore.QSize(24, 24))
        self.add_1_gauss.setFlat(True)
        self.add_1_gauss.setObjectName("add_1_gauss")
        self.verticalLayout_29.addWidget(self.add_1_gauss)
        self.del_1_gauss = QtWidgets.QPushButton(self.tab_5)
        self.del_1_gauss.setMinimumSize(QtCore.QSize(24, 24))
        self.del_1_gauss.setMaximumSize(QtCore.QSize(24, 24))
        self.del_1_gauss.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/24x24/resources/icons/arrow-minus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.del_1_gauss.setIcon(icon1)
        self.del_1_gauss.setIconSize(QtCore.QSize(24, 24))
        self.del_1_gauss.setFlat(True)
        self.del_1_gauss.setObjectName("del_1_gauss")
        self.verticalLayout_29.addWidget(self.del_1_gauss)
        self.horizontalLayout_20.addLayout(self.verticalLayout_29)
        self.verticalLayout_22.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.line_31 = QtWidgets.QFrame(self.tab_5)
        self.line_31.setMinimumSize(QtCore.QSize(50, 0))
        self.line_31.setMaximumSize(QtCore.QSize(50, 16777215))
        self.line_31.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_31.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_31.setObjectName("line_31")
        self.horizontalLayout_22.addWidget(self.line_31)
        self.DFT_label_18 = QtWidgets.QLabel(self.tab_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(150)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DFT_label_18.sizePolicy().hasHeightForWidth())
        self.DFT_label_18.setSizePolicy(sizePolicy)
        self.DFT_label_18.setMinimumSize(QtCore.QSize(120, 0))
        self.DFT_label_18.setMaximumSize(QtCore.QSize(300, 14))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.DFT_label_18.setFont(font)
        self.DFT_label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.DFT_label_18.setObjectName("DFT_label_18")
        self.horizontalLayout_22.addWidget(self.DFT_label_18)
        self.line_32 = QtWidgets.QFrame(self.tab_5)
        self.line_32.setMinimumSize(QtCore.QSize(50, 0))
        self.line_32.setMaximumSize(QtCore.QSize(50, 16777215))
        self.line_32.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_32.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_32.setObjectName("line_32")
        self.horizontalLayout_22.addWidget(self.line_32)
        self.verticalLayout_22.addLayout(self.horizontalLayout_22)
        self.verticalLayout_25 = QtWidgets.QVBoxLayout()
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.job_type_comboBox_gauss = QtWidgets.QComboBox(self.tab_5)
        self.job_type_comboBox_gauss.setMinimumSize(QtCore.QSize(100, 0))
        self.job_type_comboBox_gauss.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.job_type_comboBox_gauss.setEditable(False)
        self.job_type_comboBox_gauss.setObjectName("job_type_comboBox_gauss")
        self.verticalLayout_25.addWidget(self.job_type_comboBox_gauss)
        self.gridLayout_33 = QtWidgets.QGridLayout()
        self.gridLayout_33.setObjectName("gridLayout_33")
        self.additionalKeys2_gauss = QtWidgets.QLineEdit(self.tab_5)
        self.additionalKeys2_gauss.setMinimumSize(QtCore.QSize(190, 21))
        self.additionalKeys2_gauss.setMaximumSize(QtCore.QSize(16777215, 21))
        font = QtGui.QFont()
        font.setItalic(True)
        self.additionalKeys2_gauss.setFont(font)
        self.additionalKeys2_gauss.setText("")
        self.additionalKeys2_gauss.setObjectName("additionalKeys2_gauss")
        self.gridLayout_33.addWidget(self.additionalKeys2_gauss, 0, 0, 1, 1)
        self.add_DFT_list2_gauss = QtWidgets.QListWidget(self.tab_5)
        self.add_DFT_list2_gauss.setMinimumSize(QtCore.QSize(190, 50))
        self.add_DFT_list2_gauss.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.add_DFT_list2_gauss.setObjectName("add_DFT_list2_gauss")
        self.gridLayout_33.addWidget(self.add_DFT_list2_gauss, 1, 0, 1, 1)
        self.verticalLayout_26 = QtWidgets.QVBoxLayout()
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.add_2_gauss = QtWidgets.QPushButton(self.tab_5)
        self.add_2_gauss.setMinimumSize(QtCore.QSize(24, 24))
        self.add_2_gauss.setMaximumSize(QtCore.QSize(24, 24))
        self.add_2_gauss.setText("")
        self.add_2_gauss.setIcon(icon)
        self.add_2_gauss.setIconSize(QtCore.QSize(24, 24))
        self.add_2_gauss.setFlat(True)
        self.add_2_gauss.setObjectName("add_2_gauss")
        self.verticalLayout_26.addWidget(self.add_2_gauss)
        self.del_2_gauss = QtWidgets.QPushButton(self.tab_5)
        self.del_2_gauss.setMinimumSize(QtCore.QSize(24, 24))
        self.del_2_gauss.setMaximumSize(QtCore.QSize(24, 24))
        self.del_2_gauss.setText("")
        self.del_2_gauss.setIcon(icon1)
        self.del_2_gauss.setIconSize(QtCore.QSize(24, 24))
        self.del_2_gauss.setFlat(True)
        self.del_2_gauss.setObjectName("del_2_gauss")
        self.verticalLayout_26.addWidget(self.del_2_gauss)
        self.gridLayout_33.addLayout(self.verticalLayout_26, 1, 1, 1, 1)
        self.verticalLayout_25.addLayout(self.gridLayout_33)
        self.verticalLayout_22.addLayout(self.verticalLayout_25)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.line_33 = QtWidgets.QFrame(self.tab_5)
        self.line_33.setMinimumSize(QtCore.QSize(50, 0))
        self.line_33.setMaximumSize(QtCore.QSize(50, 16777215))
        self.line_33.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_33.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_33.setObjectName("line_33")
        self.horizontalLayout_23.addWidget(self.line_33)
        self.DFT_label_19 = QtWidgets.QLabel(self.tab_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(150)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DFT_label_19.sizePolicy().hasHeightForWidth())
        self.DFT_label_19.setSizePolicy(sizePolicy)
        self.DFT_label_19.setMinimumSize(QtCore.QSize(120, 0))
        self.DFT_label_19.setMaximumSize(QtCore.QSize(300, 14))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.DFT_label_19.setFont(font)
        self.DFT_label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.DFT_label_19.setObjectName("DFT_label_19")
        self.horizontalLayout_23.addWidget(self.DFT_label_19)
        self.line_34 = QtWidgets.QFrame(self.tab_5)
        self.line_34.setMinimumSize(QtCore.QSize(50, 0))
        self.line_34.setMaximumSize(QtCore.QSize(50, 16777215))
        self.line_34.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_34.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_34.setObjectName("line_34")
        self.horizontalLayout_23.addWidget(self.line_34)
        self.verticalLayout_22.addLayout(self.horizontalLayout_23)
        self.verticalLayout_27 = QtWidgets.QVBoxLayout()
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.gridLayout_34 = QtWidgets.QGridLayout()
        self.gridLayout_34.setObjectName("gridLayout_34")
        self.additionalKeys3_gauss = QtWidgets.QLineEdit(self.tab_5)
        self.additionalKeys3_gauss.setMinimumSize(QtCore.QSize(190, 21))
        self.additionalKeys3_gauss.setMaximumSize(QtCore.QSize(16777215, 21))
        font = QtGui.QFont()
        font.setItalic(True)
        self.additionalKeys3_gauss.setFont(font)
        self.additionalKeys3_gauss.setText("")
        self.additionalKeys3_gauss.setObjectName("additionalKeys3_gauss")
        self.gridLayout_34.addWidget(self.additionalKeys3_gauss, 0, 0, 1, 1)
        self.add_DFT_list3_gauss = QtWidgets.QListWidget(self.tab_5)
        self.add_DFT_list3_gauss.setMinimumSize(QtCore.QSize(190, 50))
        self.add_DFT_list3_gauss.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.add_DFT_list3_gauss.setObjectName("add_DFT_list3_gauss")
        self.gridLayout_34.addWidget(self.add_DFT_list3_gauss, 1, 0, 1, 1)
        self.verticalLayout_28 = QtWidgets.QVBoxLayout()
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.add_3_gauss = QtWidgets.QPushButton(self.tab_5)
        self.add_3_gauss.setMinimumSize(QtCore.QSize(24, 24))
        self.add_3_gauss.setMaximumSize(QtCore.QSize(24, 24))
        self.add_3_gauss.setText("")
        self.add_3_gauss.setIcon(icon)
        self.add_3_gauss.setIconSize(QtCore.QSize(24, 24))
        self.add_3_gauss.setFlat(True)
        self.add_3_gauss.setObjectName("add_3_gauss")
        self.verticalLayout_28.addWidget(self.add_3_gauss)
        self.del_3_gauss = QtWidgets.QPushButton(self.tab_5)
        self.del_3_gauss.setMinimumSize(QtCore.QSize(24, 24))
        self.del_3_gauss.setMaximumSize(QtCore.QSize(24, 24))
        self.del_3_gauss.setText("")
        self.del_3_gauss.setIcon(icon1)
        self.del_3_gauss.setIconSize(QtCore.QSize(24, 24))
        self.del_3_gauss.setFlat(True)
        self.del_3_gauss.setObjectName("del_3_gauss")
        self.verticalLayout_28.addWidget(self.del_3_gauss)
        self.gridLayout_34.addLayout(self.verticalLayout_28, 1, 1, 1, 1)
        self.verticalLayout_27.addLayout(self.gridLayout_34)
        self.verticalLayout_22.addLayout(self.verticalLayout_27)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.save_button_2 = QtWidgets.QPushButton(self.tab_5)
        self.save_button_2.setMinimumSize(QtCore.QSize(100, 25))
        self.save_button_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.save_button_2.setFont(font)
        self.save_button_2.setStyleSheet("QPushButton {\n"
"     background-color: rgb(143, 23, 119);\n"
"       color: white;\n"
" }\n"
" QPushButton:hover{\n"
" background-color:rgb(143, 23, 119);\n"
" border-style: outset;\n"
" border-width: 0px;\n"
" /*border-color: rgb(12, 103, 213);*/\n"
" }\n"
" QPushButton:pressed\n"
" {\n"
" /*background-color:rgb(17, 145, 255);\n"
"  color: black*/\n"
"  background-color: rgb(42, 42, 42);\n"
" }\n"
" QListWidget{\n"
" background-color: rgb(20,20,20);\n"
" border:None;\n"
" margin-top:0px;\n"
" margin-left:0px;\n"
" margin-right:0px;\n"
" }")
        self.save_button_2.setObjectName("save_button_2")
        self.horizontalLayout_24.addWidget(self.save_button_2)
        self.cancel_button_3 = QtWidgets.QPushButton(self.tab_5)
        self.cancel_button_3.setMinimumSize(QtCore.QSize(100, 25))
        self.cancel_button_3.setMaximumSize(QtCore.QSize(16777215, 25))
        self.cancel_button_3.setStyleSheet("\n"
"\n"
"QPushButton {\n"
"    /*background-color:rgb(98, 114, 164);*/\n"
"    background-color: rgb(30,30,30);\n"
"    color: rgb(143,23,119);\n"
"    \n"
"\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"       background-color: rgb(40, 40, 40);\n"
"    /*color:rgb(20,20,20);*/\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-color: rgb(143,23,119);\n"
"\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    color: rgb(143, 23, 119);\n"
"    background-color: rgb(20, 20, 20);\n"
"}\n"
"")
        self.cancel_button_3.setObjectName("cancel_button_3")
        self.horizontalLayout_24.addWidget(self.cancel_button_3)
        self.verticalLayout_22.addLayout(self.horizontalLayout_24)
        self.tabWidget_2.addTab(self.tab_5, "")
        self.verticalLayout_2.addWidget(self.tabWidget_2)
        SettingsWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(SettingsWindow)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(SettingsWindow)

    def retranslateUi(self, SettingsWindow):
        _translate = QtCore.QCoreApplication.translate
        SettingsWindow.setWindowTitle(_translate("SettingsWindow", "Settings"))
        self.DFT_label_20.setText(_translate("SettingsWindow", "General settings"))
        self.label_3.setText(_translate("SettingsWindow", "  Working directory:"))
        self.change_cwd_button.setText(_translate("SettingsWindow", "Change"))
        self.label_4.setText(_translate("SettingsWindow", "  PyMOL path:"))
        self.change_pymol_button.setText(_translate("SettingsWindow", "Change"))
        self.open_pymol_checkBox.setText(_translate("SettingsWindow", "  Open Pymol\n"
"  at launch "))
        self.DFT_label_21.setText(_translate("SettingsWindow", "Software:"))
        self.radioButton_ORCA.setText(_translate("SettingsWindow", "ORCA"))
        self.radioButton_Gaussian.setText(_translate("SettingsWindow", "Gaussian"))
        self.save_button_0.setText(_translate("SettingsWindow", "Save and close"))
        self.cancel_button_0.setText(_translate("SettingsWindow", "Cancel"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("SettingsWindow", "General"))
        self.DFT_label_6.setText(_translate("SettingsWindow", "Default DFT settings"))
        self.funct_label_5.setText(_translate("SettingsWindow", "Functional :"))
        self.basis_label_5.setText(_translate("SettingsWindow", "Basis set:"))
        self.DFT_label_14.setText(_translate("SettingsWindow", "Job-type specific keywords"))
        self.jobspec_keywords_orca.setPlaceholderText(_translate("SettingsWindow", "Write keyword here ..."))
        self.pushButton.setText(_translate("SettingsWindow", "Add"))
        self.pushButton_2.setText(_translate("SettingsWindow", "Remove selected"))
        self.DFT_label_15.setText(_translate("SettingsWindow", "Input blocks (%)"))
        self.additionalblock_orca.setPlaceholderText(_translate("SettingsWindow", "Write block content here ..."))
        self.pushButton_3.setText(_translate("SettingsWindow", "Add"))
        self.pushButton_4.setText(_translate("SettingsWindow", "Remove selected"))
        self.save_button_1.setText(_translate("SettingsWindow", "Save and close"))
        self.cancel_button_1.setText(_translate("SettingsWindow", "Cancel"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_8), _translate("SettingsWindow", "ORCA"))
        self.DFT_label_16.setText(_translate("SettingsWindow", "Default DFT settings"))
        self.funct_label_6.setText(_translate("SettingsWindow", "Functional :"))
        self.basis_label_6.setText(_translate("SettingsWindow", "Basis set:"))
        self.label_14.setText(_translate("SettingsWindow", "("))
        self.label_15.setText(_translate("SettingsWindow", " ,"))
        self.label_16.setText(_translate("SettingsWindow", " )"))
        self.DFT_label_18.setText(_translate("SettingsWindow", "Job-type specific keywords"))
        self.DFT_label_19.setText(_translate("SettingsWindow", "Link 0 commands"))
        self.save_button_2.setText(_translate("SettingsWindow", "Save and close"))
        self.cancel_button_3.setText(_translate("SettingsWindow", "Cancel"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("SettingsWindow", "Gaussian"))

import icons_rc
