  name: Build Ubuntu binary with pyinstaller
  on: push

  jobs:
    build-and-deploy:
      name: Build
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Install python
          uses: actions/setup-python@v1
          with:
            python-version: 3.8
        - name: Install dependencies
          run: |
            pip install -r requirements.txt
            pip install pyinstaller
        - name: Build binary
          run: |
            pyinstaller REACT_linux.spec
        - name: Commit and push to REACT_macos
          run: |-
            git config --global user.email "workflow-bot@example.com"
            git config --global user.name "workflow-bot"
            mv dist/REACT bundles/REACT
            git checkout --orphan build_deoploy
            git add bundles/*
            git commit -m "build with ubuntu-latest"
            git push --set-upstream origin clean_directory_three --force
