  name: Build MacOS app with pyinstaller
  on: push

  jobs:
    build-and-deploy:
      name: Build
      runs-on: macos-latest
      steps:
        - uses: actions/checkout@v2
        - name: Install python
          uses: actions/setup-python@v1
          with:
            python-version: 3.8
        - name: Install dependencies
          run: |
            pip install -r requirements.txt
            pip install pyinstaller
        - name: Build binary
          run: |
            pyinstaller REACT_darvin.spec

        - name: Deploy build
          if: success()
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: testing
